### PR TITLE
remove testsuite-generated from source control

### PR DESCRIPTION
**Pull request by marler8997**
Builds wast2json using the upstream WebAssembly source and some build.zig and uses that to generate the testsuite json files on demand.

Tested on macOS/Windows and linux.

### CODE REVIEW

**Comment by malcolmstill** [comment]
@marler8997 this is great, love the approach of building wast2json from source (which nicely solves why I added the blobs in the first place, which if I recall correctly was to avoid depending on the tools via apt get).

**Comment by malcolmstill** [comment]
Also I've changed the repo settings so the CI should kick in now automatically if you make a PR

**Comment by marler8997** [comment]
Looks like the `parsecheck` step/tool were validating the output of wast2json?  If so, we could probably remove that check from the CI correct since the testsuite itself would validate the output correct?

**Comment by malcolmstill** [comment]
@marler8997 I'm trying to understand why `parsecheck` was added in the first place; from https://github.com/malcolmstill/zware/pull/168 looks like it was maybe for testing that parsing never crashes (even for features that were yet to be supported) and I also see that it I was saving `.wasm` blobs that I had generated through fuzz testing that had highlighted bugs in the parser.

I'll have a think about that latter point (of the fuzzed examples) and maybe you can let me know your thoughts, but I'm happy to just remove this code for the moment (it's a trivial amount of code)

**Pull request merged**
